package com.p2b.front.entity;

public class Custom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_id
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.userid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_name
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_phone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String customPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_age
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long customAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.marry_status
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String marryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.province
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_id
     *
     * @return the value of custom.custom_id
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_id
     *
     * @param customId the value for custom.custom_id
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setCustomId(Long customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.userid
     *
     * @return the value of custom.userid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.userid
     *
     * @param userid the value for custom.userid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_name
     *
     * @return the value of custom.custom_name
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_name
     *
     * @param customName the value for custom.custom_name
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_phone
     *
     * @return the value of custom.custom_phone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getCustomPhone() {
        return customPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_phone
     *
     * @param customPhone the value for custom.custom_phone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setCustomPhone(String customPhone) {
        this.customPhone = customPhone == null ? null : customPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_age
     *
     * @return the value of custom.custom_age
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getCustomAge() {
        return customAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_age
     *
     * @param customAge the value for custom.custom_age
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setCustomAge(Long customAge) {
        this.customAge = customAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.marry_status
     *
     * @return the value of custom.marry_status
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getMarryStatus() {
        return marryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.marry_status
     *
     * @param marryStatus the value for custom.marry_status
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setMarryStatus(String marryStatus) {
        this.marryStatus = marryStatus == null ? null : marryStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.province
     *
     * @return the value of custom.province
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.province
     *
     * @param province the value for custom.province
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }
}