package com.p2b.front.entity;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long managerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.name
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.phone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.grade
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.state
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.idcard
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.idphoto
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String idphoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerid
     *
     * @return the value of manager.managerid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerid
     *
     * @param managerid the value for manager.managerid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setManagerid(Long managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.name
     *
     * @return the value of manager.name
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.name
     *
     * @param name the value for manager.name
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.phone
     *
     * @return the value of manager.phone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.phone
     *
     * @param phone the value for manager.phone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.grade
     *
     * @return the value of manager.grade
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.grade
     *
     * @param grade the value for manager.grade
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.state
     *
     * @return the value of manager.state
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.state
     *
     * @param state the value for manager.state
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.idcard
     *
     * @return the value of manager.idcard
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.idcard
     *
     * @param idcard the value for manager.idcard
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.idphoto
     *
     * @return the value of manager.idphoto
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getIdphoto() {
        return idphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.idphoto
     *
     * @param idphoto the value for manager.idphoto
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setIdphoto(String idphoto) {
        this.idphoto = idphoto == null ? null : idphoto.trim();
    }
}