package com.p2b.front.entity;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_feature
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String productFeature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.max_money
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Double maxMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.money_time
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long moneyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_company
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String productCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_logo
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String productLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_identity
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String productIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_words
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String productWords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.for_people
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String forPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.money_use
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String moneyUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.money
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.money_con
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String moneyCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.reward
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String reward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.process
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.state
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_id
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_id
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long updateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productid
     *
     * @return the value of product.productid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productid
     *
     * @param productid the value for product.productid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_feature
     *
     * @return the value of product.product_feature
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getProductFeature() {
        return productFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_feature
     *
     * @param productFeature the value for product.product_feature
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setProductFeature(String productFeature) {
        this.productFeature = productFeature == null ? null : productFeature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.max_money
     *
     * @return the value of product.max_money
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Double getMaxMoney() {
        return maxMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.max_money
     *
     * @param maxMoney the value for product.max_money
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setMaxMoney(Double maxMoney) {
        this.maxMoney = maxMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.money_time
     *
     * @return the value of product.money_time
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getMoneyTime() {
        return moneyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.money_time
     *
     * @param moneyTime the value for product.money_time
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setMoneyTime(Long moneyTime) {
        this.moneyTime = moneyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_company
     *
     * @return the value of product.product_company
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getProductCompany() {
        return productCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_company
     *
     * @param productCompany the value for product.product_company
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setProductCompany(String productCompany) {
        this.productCompany = productCompany == null ? null : productCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_logo
     *
     * @return the value of product.product_logo
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getProductLogo() {
        return productLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_logo
     *
     * @param productLogo the value for product.product_logo
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setProductLogo(String productLogo) {
        this.productLogo = productLogo == null ? null : productLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_identity
     *
     * @return the value of product.product_identity
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getProductIdentity() {
        return productIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_identity
     *
     * @param productIdentity the value for product.product_identity
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setProductIdentity(String productIdentity) {
        this.productIdentity = productIdentity == null ? null : productIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_words
     *
     * @return the value of product.product_words
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getProductWords() {
        return productWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_words
     *
     * @param productWords the value for product.product_words
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setProductWords(String productWords) {
        this.productWords = productWords == null ? null : productWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.for_people
     *
     * @return the value of product.for_people
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getForPeople() {
        return forPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.for_people
     *
     * @param forPeople the value for product.for_people
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setForPeople(String forPeople) {
        this.forPeople = forPeople == null ? null : forPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.money_use
     *
     * @return the value of product.money_use
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getMoneyUse() {
        return moneyUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.money_use
     *
     * @param moneyUse the value for product.money_use
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setMoneyUse(String moneyUse) {
        this.moneyUse = moneyUse == null ? null : moneyUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.money
     *
     * @return the value of product.money
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.money
     *
     * @param money the value for product.money
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.money_con
     *
     * @return the value of product.money_con
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getMoneyCon() {
        return moneyCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.money_con
     *
     * @param moneyCon the value for product.money_con
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setMoneyCon(String moneyCon) {
        this.moneyCon = moneyCon == null ? null : moneyCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.reward
     *
     * @return the value of product.reward
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.reward
     *
     * @param reward the value for product.reward
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setReward(String reward) {
        this.reward = reward == null ? null : reward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.process
     *
     * @return the value of product.process
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.process
     *
     * @param process the value for product.process
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setProcess(String process) {
        this.process = process == null ? null : process.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.state
     *
     * @return the value of product.state
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.state
     *
     * @param state the value for product.state
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_id
     *
     * @return the value of product.create_id
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_id
     *
     * @param createId the value for product.create_id
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_id
     *
     * @return the value of product.update_id
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_id
     *
     * @param updateId the value for product.update_id
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }
}