package com.p2b.front.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.state
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.grade
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.idcard
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.idphoto
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String idphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.managerid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private Long managerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mphone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String mphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bank_account
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bank
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bank_image
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    private String bankImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.state
     *
     * @return the value of user.state
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.state
     *
     * @param state the value for user.state
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.grade
     *
     * @return the value of user.grade
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.grade
     *
     * @param grade the value for user.grade
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.idcard
     *
     * @return the value of user.idcard
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.idcard
     *
     * @param idcard the value for user.idcard
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.idphoto
     *
     * @return the value of user.idphoto
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getIdphoto() {
        return idphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.idphoto
     *
     * @param idphoto the value for user.idphoto
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setIdphoto(String idphoto) {
        this.idphoto = idphoto == null ? null : idphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.managerid
     *
     * @return the value of user.managerid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public Long getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.managerid
     *
     * @param managerid the value for user.managerid
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setManagerid(Long managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mphone
     *
     * @return the value of user.mphone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getMphone() {
        return mphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mphone
     *
     * @param mphone the value for user.mphone
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setMphone(String mphone) {
        this.mphone = mphone == null ? null : mphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bank_account
     *
     * @return the value of user.bank_account
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bank_account
     *
     * @param bankAccount the value for user.bank_account
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bank
     *
     * @return the value of user.bank
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bank
     *
     * @param bank the value for user.bank
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bank_image
     *
     * @return the value of user.bank_image
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public String getBankImage() {
        return bankImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bank_image
     *
     * @param bankImage the value for user.bank_image
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    public void setBankImage(String bankImage) {
        this.bankImage = bankImage == null ? null : bankImage.trim();
    }
}