package com.p2b.front.dao;

import com.p2b.front.entity.Manager;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int deleteByPrimaryKey(Long managerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    Manager selectByPrimaryKey(Long managerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int updateByPrimaryKey(Manager record);
}