package com.p2b.front.dao;

import com.p2b.front.entity.Product;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int deleteByPrimaryKey(Long productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    Product selectByPrimaryKey(Long productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int updateByPrimaryKey(Product record);
}