package com.p2b.front.dao;

import java.util.List;

import com.p2b.front.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    User selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Jan 26 13:46:48 CST 2018
     */
    int updateByPrimaryKey(User record);
    
    List<User> queryAllUser();
	
	int countByPhone(String phone);	//得到该手机号码注册的业务员数量

	User selectByPhone(String phone);//得到该手机号码注册的user对象
}